name: common_check
on:
  push:
    branches-ignore:
      - develop
  pull_request:
    branches-ignore:
      - develop
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: execute check styles
        run: python tests/code-style/check.py
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libatk1.0-0 libcups2 libatk-bridge2.0-0 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libnss3 libgbm1 libasound2

      - name: check out repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
            node-version: 18
      
      - name: Run unit tests
        run: |
          npm install grunt-cli node-qunit-puppeteer
          npm install --prefix build
          node node_modules/grunt-cli/bin/grunt --gruntfile build/Gruntfile.js develop
          node node_modules/node-qunit-puppeteer/cli.js tests/common/api/api.html
  builder-tests:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v4
        with:
          path: sdkjs

      - name: check out repository sdkjs-forms current branch
        id: sdkjs-forms
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          repository: ONLYOFFICE/sdkjs-forms
          token: ${{ secrets.READ_PAT }}
          path: sdkjs-forms
          ref: ${{ github.ref }}
      - name: check out repository sdkjs-forms master branch
        if: steps.sdkjs-forms.outcome != 'success'
        uses: actions/checkout@v4
        with:
          repository: ONLYOFFICE/sdkjs-forms
          token: ${{ secrets.READ_PAT }}
          path: sdkjs-forms
          ref: master

      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Run builder tests
        run: |
          cd sdkjs
          npm install -g grunt-cli
          npm install --prefix build
          grunt --level=WHITESPACE_ONLY --addon=sdkjs-forms --base build --gruntfile build/Gruntfile.js
          docker run -v $PWD/deploy/sdkjs/common:/opt/onlyoffice/documentbuilder/sdkjs/common \
                     -v $PWD/deploy/sdkjs/word:/opt/onlyoffice/documentbuilder/sdkjs/word \
                     -v $PWD/deploy/sdkjs/cell:/opt/onlyoffice/documentbuilder/sdkjs/cell \
                     -v $PWD/deploy/sdkjs/slide:/opt/onlyoffice/documentbuilder/sdkjs/slide \
                     onlyoffice/doc-builder-testing:next-release rake rspec_critical
